image: g3org3/node
script:
  - cd app
  - npm install
  - npm test
  - echo "done"

publish:
  docker:
    username: g3org3
    password: $$password
    email: $$email
    repo: $$image

deploy:
  rancher:
    url: $$url
    access_key: $$access_key
    secret_key: $$secret_key
    service: $$service
    docker_image: $$image
