image: g3org3/node
script:
  - cd app
  - npm install
  - npm test
  - echo "done"

publish:
  docker:
    username: g3org3
    password: $$password
    email: $$email
    repo: g3org3/fun

deploy:
  tutum:
    username: g3org3
    api_key: $$API_KEY
    image: g3org3/fun
    redeploy: true
    reuse_volumes: true
