image: g3org3/node
script:
  - export REDIS='redis'
  - cd app
  - npm install
  - npm test
  - echo "done"

deploy:
  tutum:
    username: g3org3
    api_key: "$$API_KEY"
    service: drone
    image: g3org3/fun:lastest
    redeploy: true

compose:
  redis:
    image: redis
