build:
  image: g3org3/node
  commands:
    - export REDIS='redis'
    - cd app
    - npm install
    - npm test
    - echo "done"

compose:
  redis:
    image: redis

publish:
  docker:
    username: g3org3
    password: $$password
    email: $$email
    repo: g3org3/fun
