image: g3org3/node
script:
  - cd app
  - npm install
  - npm test
  - echo "done"

deploy:
  tutum:
    username: g3org3
    api_key: $$API_KEY
    service: drone
    image: $$image
    redeploy: true
