build:
  image: g3org3/node
  commands:
    - export REDIS=localhost
    - export TUTUM_USER="$$TUTUM_USER"
    - export TUTUM_APIKEY="$$TUTUM_APIKEY"
    - cd app
    - npm install
    - npm test
    - echo "done"

compose:
  redis:
    image: redis

# publish:
#   docker:
#     username: g3org3
#     password: $$password
#     email: $$email
#     repo: g3org3/fun

deploy:
  tutum:
    username: "$$TUTUM_USER"
    api_key: "$$TUTUM_APIKEY"
    docker_image: tutum.co/g3org3/fun
    redeploy: true
    reuse_volumes: true
